version: "3"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=
      - POSTGRES_DB=
    ports:
      - "5432:5432"
    volumes:
      - /home/bob/podman_docker/cours/Becq-e-master/batiments.sql:/docker-entrypoint-initdb.d/create_tables.sql
  
    
  api:
    image: cowbra/esilv:tuco-server
    restart: always
    volumes:
      - server:/app/node_modules
      - /home/bob/podman_docker/cours/Becq-e-master/server:/app
    environment:
      - PGUSER=
      - PGHOST=postgres
      - PGDATABASE=becq_e
      - PGPASSWORD=
      - PGPORT=5432
    links:
      - postgres
    depends_on:
      - postgres

      
  client:
    image: cowbra/esilv:tuco-client
    restart: always
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - client:/app/node_modules
      - /home/bob/podman_docker/cours/Becq-e-master/client:/app
    links:
      - api
    depends_on:
      - postgres
      - api

      
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: cowbra/esilv:tuco-nginx
    expose:
      - "80"
    networks:
      - nginx-proxy-manager_default
      - default

volumes:
  client:
  server:

networks:
  nginx-proxy-manager_default:
    name: nginx-proxy-manager_default
    external: true
