# Specify the image that will be used as a base for our build
FROM nginx
# copy this file from the local directory to the working directory of the container
COPY ./default.conf /etc/nginx/conf.d/default.conf